version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: domainbadger
    main: ./cmd/domainbadger
    binary: domainbadger
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w 
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - repository:
      owner: emmanuelay
      name: homebrew-tap
    directory: Formula
    
    url_template: "https://github.com/emmanuelay/domainbadger/archive/{{ .Tag }}.tar.gz"
    
    homepage: "https://github.com/emmanuelay/domainbadger"
    description: "CLI tool for domain information lookup"
    license: "MIT"
    
    dependencies:
      - name: go
        type: build
    
    install: |
      system "go", "build", "-ldflags",
             "-s -w -X main.version=#{version}",
             "-o", bin/"domainbadger",
             "./cmd/domainbadger"
    
    test: |
      assert_match version.to_s, shell_output("#{bin}/domainbadger --version")